# Generated by Django 5.2.6 on 2025-09-05 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('payment_method', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money'), ('CASH', 'Paiement à la Livraison'), ('SHOP', 'Paiement en Boutique')], max_length=10, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PROCESSING', 'En traitement'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('shipping_address', models.TextField(verbose_name='Adresse de livraison')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('main_color', models.CharField(choices=[('RED', 'Rouge'), ('BLK', 'Noir'), ('WHT', 'Blanc'), ('BLU', 'Bleu'), ('GRN', 'Vert'), ('YLW', 'Jaune'), ('GRY', 'Gris'), ('BRW', 'Marron'), ('PNK', 'Rose'), ('PRP', 'Violet'), ('ORG', 'Orange'), ('MUL', 'Multicolor')], max_length=3, verbose_name='Couleur principale')),
                ('available_colors', models.CharField(help_text='Séparer les couleurs par des virgules', max_length=100, verbose_name='Couleurs disponibles')),
                ('min_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(50)], verbose_name='Pointure minimale')),
                ('max_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(50)], verbose_name='Pointure maximale')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(upload_to='shoes/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Chaussure',
                'verbose_name_plural': 'Chaussures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('size', models.IntegerField(verbose_name='Pointure')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.order', verbose_name='Commande')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe', verbose_name='Chaussure')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shoes.OrderItem', to='shoes.shoe', verbose_name='Articles'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('city', models.CharField(blank=True, choices=[('DOUALA', 'Douala'), ('YAOUNDE', 'Yaoundé'), ('GAROUA', 'Garoua'), ('BAMENDA', 'Bamenda'), ('MAROUA', 'Maroua'), ('NKOUNGSAMBA', 'Nkongsamba'), ('BAFOUSSAM', 'Bafoussam'), ('NGAOUNDERE', 'Ngaoundéré'), ('BERTOUA', 'Bertoua'), ('LIMBE', 'Limbé'), ('EDEA', 'Edéa'), ('KUMBA', 'Kumba'), ('MBALMAYO', 'Mbalmayo'), ('DSCHANG', 'Dschang'), ('FOUMBAN', 'Foumban')], max_length=50, verbose_name='Ville')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
