# Generated by Django 5.2.6 on 2025-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
