# Generated by Django 5.2.6 on 2025-09-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_contactmessage_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
    ]
