# Generated by Django 5.2.6 on 2025-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_contactmessage_is_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
