# Generated by Django 5.2.6 on 2025-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_alter_shoe_image_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmation_message',
            field=models.TextField(blank=True, help_text='Collez ici le message reçu après paiement via MTN ou Orange Money', verbose_name='Message de confirmation de paiement'),
        ),
    ]
