# Generated by Django 5.2.6 on 2025-09-18 21:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_order_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_images', to='shoes.shoe', verbose_name='Chaussure')),
            ],
            options={
                'verbose_name': 'Image de chaussure',
                'verbose_name_plural': 'Images de chaussures',
            },
        ),
    ]
